FROM python:3-alpine

WORKDIR /python-docker

EXPOSE 5000

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

CMD [ "flask", "--app" , "src/app.py", "run", "--host", "0.0.0.0", "--port", "5000", "--no-reload"]
